import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useEffect, useState } from "react";
import { Dark } from "../components/Dark";
import { MovieCard } from "../components/movieCard";
import { SearchMovie } from "../components/SearchMovie";
import { ActorAgeComponent } from "../components/ActorAgeComponent";
import { ActorCard } from "../components/ActorCard";

export default function Home() {
  // import api key from .env file

  // state for moviews
  const [movies, setMovies] = useState([]);
  const [actors, setActors] = useState([]);

  //  create function that fetches
  //  data from the API
  const fetchData = async () => {
    const baseUrl = "https://api.themoviedb.org/3/";
    const key = "b00fb54297384d5eaa45556b05fbb775";

    const url = baseUrl + "movie/popular?api_key=" + key;
    // use axios to fetch the data
    const response = await axios.get(url);
    const movies = response.data.results;
    // get trending actors
    const url2 = baseUrl + "person/popular?api_key=" + key;
    const response2 = await axios.get(url2);
    const actors = response2.data.results;

    console.log("movies", movies);
    setMovies(movies.slice(0, 12));
    setActors(actors.slice(0, 12));

    return movies;
  };

  // run fetchData function in useEffect
  useEffect(() => {
    fetchData();
  }, []);

  return (
    <main className="h-screen  m-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto max-w-7xl p-8 rounded-md">
        <h1 className="">How Old Were They?</h1>
        <p className="text-slate-300">
          Are you ever watching a movie and wonder how old an actor or actress
          was when it was filmed?
        </p>

        {/* input to search for a movie */}
        <div className="flex justify-center">
          <SearchMovie />
        </div>

        <div>
          <h3 className="">Popular Movies</h3>

          <div className="grid grid-cols-6">
            {movies &&
              movies.map((movie) => <MovieCard movie={movie} key={movie.id} />)}
          </div>
        </div>

        <div>
          <h3 className="">Popular Actors</h3>

          <div className="grid grid-cols-6">
            {actors &&
              actors.map((actor) => <ActorCard actor={actor} key={actor.id} />)}
          </div>
        </div>
      </div>
    </main>
  );
}
